spring:
  security:
    user:
      name: user
      password: pass

server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: Turkish@59
    keyStoreType: PKCS12
    keyAlias: tomcat