spring:
  security:
    user:
      name: user
      password: pass

server:
  port: 8080 # change back to 443 later
  # ssl:
  #   key-store: keystore.p12
  #   key-store-password: Turkish@59
  #   keyStoreType: PKCS12
  #   keyAlias: tomcat